exman2020/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("feedback.urls")),
    path('', include("expenses.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

expenses/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = "expenses"

router = routers.DefaultRouter()
router.register(r'expense', views.ExpenseViewSet)
router.register(r'category', views.CategoryViewSet)

urlpatterns = [
    # path('', views.expense_list, name="list"),
    path('', views.ExpenseListView.as_view(), name="list"),
    path('joke/', views.joke_view, name="joke"),
    path('best-joke-api/', views.best_joke_json_view, name="joke_json"),
    # path('trivia/', views.trivia_view, name="trivia/"),
    path('create/', views.expense_create, name="create"),
    path('create-react/', views.expense_create_react, name="create_react"),
    path('<int:id>/', views.expense_detail, name="detail"),
    path('<int:id>/star/', views.expense_star, name="star"),

    path('api/expenses/', views.expense_json_list, name="json_list"),
    path('autoapi/', include(router.urls)),
]

feedback/urls.py
from django.urls import path

from . import views

app_name = "feedback"

urlpatterns = [
    path('contact-us/', views.contact_us_view, name="contact"),
]

expenses/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)
    priority = models.IntegerField(default=5)

    def __str__(self):
        return self.name

    def is_important(self):
        return self.priority <= 2


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="expenses")
    category = models.ForeignKey(Category, on_delete=models.PROTECT,
                                 related_name="expenses")
    date = models.DateField()
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_star = models.BooleanField(default=False)

    def __str__(self):
        return f"[#{self.id}] ${self.amount}@{self.date}: {self.title}"

feedback/models.py
from django.db import models

# Create your models here.

pokemons/models.py
from django.db import models


class Pokemon(models.Model):
    name = models.CharField(max_length=100, unique=True)
    level = models.IntegerField(default=1)

expenses/forms.py
from django import forms

from . import models

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = models.Expense
        # fields = '__all__'
        exclude = [
            'user',
        ]

feedback/forms.py
from django import forms


class ContactUsForm(forms.Form):
    birthday = forms.DateField()
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    number_of_children = forms.IntegerField(initial=3)
    message = forms.CharField(widget=forms.Textarea())

expenses/views.py
import logging
import logging
import random

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from rest_framework.viewsets import ModelViewSet

from expenses import forms
from expenses.models import Expense, Category
from expenses.serializers import ExpenseSerializer, CategorySerializer

logger = logging.getLogger(__name__)


def joke_view(request):
    return render(request, "jokes.html", {

    })


def best_joke_json_view(request):
    # import time
    # time.sleep(3)
    n = random.randint(2, 100)
    payload = {
        'id': "sakdjhaskjdh",
        'joke': f'How can you put {n} elephants in a beetle?',
    }
    return JsonResponse(payload)


# @login_required
# def expense_list(request):
#     qs = Expense.objects.filter(user=request.user).order_by('-date')[:12]
#     # FIXME: use sql group by sum???
#     total = sum([x.amount for x in qs])
#     return render(request, "expenses/expense_list.html", {
#         'object_list': qs,
#         'total': total,
#     })

#
# see: https://docs.djangoproject.com/en/3.0/topics/class-based-views/ and https://ccbv.co.uk/
class ExpenseListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user).order_by('-date')

    def total(self):
        qs = self.get_queryset()
        return sum([x.amount for x in qs])


@login_required
def expense_list(request):
    qs = Expense.objects.filter(user=request.user).order_by('-date')[:12]
    # FIXME: use sql group by sum???
    total = sum([x.amount for x in qs])
    return render(request, "expenses/expense_list.html", {
        'object_list': qs,
        'total': total,
    })


@login_required
def expense_detail(request, id):
    o = get_object_or_404(Expense, id=id, user=request.user)

    return render(request, "expenses/expense_detail.html", {
        'object': o,
    })


@login_required
def expense_star(request, id):
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    import time
    time.sleep(2.5)
    o = get_object_or_404(Expense, id=id)
    logger.warning(f"STARING EXPENSE #{id}, {o}")
    o.is_star = True
    o.save()
    return JsonResponse({'status': 'OK'})


@login_required
def expense_create(request):
    # if not request.user.userprofile.is_manager:
    #     return redirect("hell")
    if request.method == "POST":
        form = forms.ExpenseForm(request.POST)
        if form.is_valid():
            # data = form.cleaned_data
            form.instance.user = request.user
            o = form.save()
            messages.success(request, f"Expense #{o.id} added. Thank you so very much!!!!!")
            # return redirect(o)  # TODO: implement get_absolute_url
            return redirect("expenses:list")

    else:
        form = forms.ExpenseForm()
    return render(request, "expenses/expense_form.html", {
        'form': form,
    })


@login_required
def expense_create_react(request):
    # if not request.user.userprofile.is_manager:
    #     return redirect("hell")
    if request.method == "POST":
        form = forms.ExpenseForm(request.POST)
        if form.is_valid():
            # data = form.cleaned_data
            form.instance.user = request.user
            o = form.save()
            messages.success(request, f"Expense #{o.id} added. Thank you so very much!!!!!")
            # return redirect(o)  # TODO: implement get_absolute_url
            return redirect("expenses:list")

    else:
        form = forms.ExpenseForm()
    return render(request, "expenses/expense_form_react.html", {
        'form': form,
    })


@login_required
def expense_json_list(request):
    qs = Expense.objects.filter(user=request.user).order_by('-date')[:12]
    ser = ExpenseSerializer(qs, many=True)
    return JsonResponse({'expenses': ser.data})


class ExpenseViewSet(ModelViewSet):
    serializer_class = ExpenseSerializer
    queryset = Expense.objects.all()

class CategoryViewSet(ModelViewSet):
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

feedback/views.py
from django.contrib import messages
from django.core.mail import mail_admins
from django.shortcuts import render, redirect

from . import forms


def contact_us_view(request):
    if request.method == "POST":
        form = forms.ContactUsForm(request.POST)
        ## form is a bound form
        if form.is_valid():
            # print(request.POST)
            # print(form.cleaned_data)

            # 3: POST + VALID:
            data = form.cleaned_data
            # o = Feedback()
            # o.birthday = data['birthday']
            # o.save()
            mail_admins(f"feedback from {data['name']}", data['message'])
            messages.success(request, "Your feeback has been sent")
            return redirect("expenses:list")

        # 2: POST+invalid ... next line: render.
    else:
        # 1 GET
        form = forms.ContactUsForm()
        # form is unbound
    return render(request, "feedback/contact_us_form.html", {
        'form': form,
    })

pokemons/views.py
from django.shortcuts import render

# Create your views here.

expenses/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="{% static "vendor/bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title>{% block title %}PO TIDCHUF TITLE{% endblock %}</title>
</head>

<body>
<div class="container-fluid">
    <nav class="navbar navbar-light bg-light navbar-expand">
        <a class="navbar-brand" href="{% url "expenses:list" %}">ExMan2020</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                    <span class="navbar-text">
                        USER: {{ user }} (#{{ user.id }})
                    </span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "logout" %}">
                            Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "login" %}">
                            Login
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "expenses:create" %}">
                        Create Expense
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "feedback:contact" %}">Contact
                        us</a>
                </li>
            </ul>
        </div>
    </nav>



    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}PO TIDCHUF CONTENT{% endblock %}

    <footer>
        Copyright 2020
    </footer>

    {% block scripts %}

    {% endblock %}

</div>
</body>

</html>

expenses/templates/expenses/expense_detail.html
{% extends "base.html" %}

{% block title %}
    Expense #{{ object.id }}
{% endblock %}

{% block content %}
    <h1>Expense #{{ object.id }} {{ object.user }}</h1>

    <div>
        <p>

            {{ object.title }}, at {{ object.date }}: ${{ object.amount }}
        </p>
        <p>
            Description:
            {{ object.description|linebreaksbr }}
        </p>
    </div>
{% endblock %}

expenses/templates/expenses/expense_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}
    Add Expense
{% endblock %}

{% block content %}
    <h1>Add Expense</h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary">Add</button>
        </form>
    </div>
{% endblock %}

expenses/templates/expenses/expense_form_react.html
{% extends "base.html" %}
{% load static  %}

{% block title %}
    Add Expense via REACT
{% endblock %}

{% block content %}
    <h1>Add Expense via REACT</h1>

    <div id="main"></div>

{% endblock %}

{% block scripts %}
    <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    <script src="{% static "react_form/expense_form_react.js" %}" type="text/babel"></script>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    My Expenses
{% endblock %}

{% block content %}
    <h1>My Expenses</h1>

    <table class="table table-hover table-bordered">
        <tr>
            <th>id</th>
            <th>title</th>
            <th>date</th>
            <th>amount</th>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url "expenses:detail" object.id %}">
                        {{ object.id }}
                    </a>
                    <span class="star" data-url="{% url "expenses:star" object.id %}">
                        {% if object.is_star %}
                            🌟
                        {% else %}
                            ⚝
                        {% endif %}
                    </span>
                </td>
                <td>{{ object.title }}</td>
                <td>{{ object.date }}</td>
                <td>${{ object.amount }}</td>
            </tr>
        {% endfor %}
        <tr>
            <th colspan="3">Total:</th>
            <th>${{ view.total }}</th>
        </tr>
    </table>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/star.js" %}"></script>
{% endblock %}

expenses/templates/fun.html
{% comment %}
    squares = [(x, x**2) for x in range(10)]
    grays = [x for x in range(0, 257, 16)]
{% endcomment %}

{% for x in view.grays %}
    <div style="clear:left">
        {% for y in view.grays %}
            <div style="width:20px;  float:left; background: rgb({{ x }},0,{{ y }})">
            </div>
        {% endfor %}
    </div>

    <p>
        {% for n, n2 in view.squares %}
            {{ n }}<sup>2</sup> = <b>{{ n2 }}</b>
            {% if not forloop.last %}
                &int;
            {% endif %}
        {% endfor %}
    </p>

{% endfor %}

expenses/templates/jokes.html
{% load static %}

<h1>Best Dad Joke Ever</h1>

<button id="get-joke">Click me to get a joke</button>
<p></p>
<p></p>
<p></p>
<p></p>
<div id="joke">THE JOKE WILL APPEAR HERE</div>

<script src="{% static "js/joke.js" %}"></script>

expenses/templates/trivia.html
{% load static %}

<h1>TRIVIA!!!!</h1>

<button id="new-question">
    CLICK TO GET A NEW QUESTION
</button>
<p></p>
<p></p>
<p></p>
<div id="question">
    SHOW QUESTION HERE
</div>

<script src="{% static "js/trivia.js" %}"></script>

feedback/templates/feedback/contact_us_form.html
{% extends "base.html" %}

{% block title %}
    Contact Us
{% endblock %}

{% block content %}
    <h1>Contact Us</h1>

    <div>
        <form method="post" novalidate>
            {% csrf_token %}
            <ul>
                {{ form.as_ul }}
            </ul>
            <button>Send feedback</button>
        </form>
    </div>
{% endblock %}